import fs from "node:fs";
import vm from "node:vm";

const dataFiles = [
  "data/chem-data.js",
  "data/reagent-extension.js",
  "data/research-data.js",
  "data/dossier-data.js",
  "data/method-data.js",
  "data/spectroscopy-data.js",
  "data/materials-data.js",
  "data/database-expansion.js",
  "data/reagent-megalibrary.js",
  "data/knowledge-expansion.js",
  "data/external-sources.js",
  "scripts/record-utils.js"
];

const context = {
  window: {},
  location: { pathname: "/pages/search.html" },
  localStorage: {
    getItem() {
      return "[]";
    }
  },
  encodeURIComponent,
  console
};
context.globalThis = context.window;
context.window.location = context.location;
context.window.localStorage = context.localStorage;
vm.createContext(context);

for (const file of dataFiles) {
  vm.runInContext(fs.readFileSync(file, "utf8"), context, { filename: file });
}

const api = context.window.CHEMVAULT_RECORDS;
if (!api?.buildRecords) {
  throw new Error("CHEMVAULT_RECORDS.buildRecords was not available.");
}

const seen = new Set();
const records = api.buildRecords({ includeImported: false }).filter((record) => {
  const key = `${record.type}:${record.id}`;
  if (seen.has(key)) return false;
  seen.add(key);
  return true;
}).map((record) => ({
  recordKey: `${record.type}:${record.id}`,
  id: record.id,
  type: record.type,
  typeLabel: record.typeLabel || record.type,
  title: record.title,
  subtitle: record.subtitle || "",
  body: record.body || "",
  domain: record.domain || "",
  family: record.family || "",
  risk: record.risk || "",
  maturity: Number(record.maturity || 0),
  formula: record.formula || "",
  tags: record.tags || [],
  href: record.href || `/pages/record.html?type=${encodeURIComponent(record.type)}&id=${encodeURIComponent(record.id)}`,
  sourceHref: record.sourceHref || "",
  imageUrl: record.imageUrl || api.recordImage(record.typeLabel || record.type, record.title, record.subtitle || record.family || record.domain || record.formula || ""),
  raw: record.raw || {},
  searchText: record.searchText || ""
}));

const lines = [
  "-- Generated by scripts/export-d1-seed.mjs",
  `-- Records: ${records.length}`,
  "BEGIN TRANSACTION;"
];

for (const record of records) {
  lines.push(`INSERT OR REPLACE INTO records (
  record_key, id, type, type_label, title, subtitle, body, domain, family, risk,
  maturity, formula, tags_json, href, source_href, image_url, raw_json, search_text
) VALUES (
  ${sql(record.recordKey)},
  ${sql(record.id)},
  ${sql(record.type)},
  ${sql(record.typeLabel)},
  ${sql(record.title)},
  ${sql(record.subtitle)},
  ${sql(record.body)},
  ${sql(record.domain)},
  ${sql(record.family)},
  ${sql(record.risk)},
  ${Number.isFinite(record.maturity) ? Math.trunc(record.maturity) : 0},
  ${sql(record.formula)},
  ${sql(JSON.stringify(record.tags))},
  ${sql(record.href)},
  ${sql(record.sourceHref)},
  ${sql(record.imageUrl)},
  ${sql(JSON.stringify(record.raw))},
  ${sql(record.searchText)}
);`);
}

lines.push("COMMIT;");
fs.writeFileSync("seed.sql", `${lines.join("\n")}\n`);

console.log(JSON.stringify({
  records: records.length,
  types: records.reduce((counts, record) => {
    counts[record.type] = (counts[record.type] || 0) + 1;
    return counts;
  }, {})
}, null, 2));

function sql(value) {
  if (value === undefined || value === null) return "''";
  return `'${String(value).replace(/'/g, "''")}'`;
}
